### ISSUE TITLE
1.0.5版本播放视频导致手机卡死

### ISSUE THREAD

**Issue by xiao-gy** [awara-app/awara#10]
> 试试1.0.5 @liyonge5

我用1.0.5会在刚开始播放视频手机卡死，但确实有声音在后台播放

_Originally posted by @xiao-gy in https://github.com/awara-app/awara/issues/9#issuecomment-1529082652_

**Comment by xiao-gy** [comment]
实际显示效果是视频只显示上面的1/4，随后手机卡死，后台视频音频播放

**Comment by xiao-gy** [comment]
> 实际显示效果是视频只显示上面的1/4，随后手机卡死，后台视频音频播放

刚才试了下，好像只有一个视频会稳定触发这个bug [视频地址](https://www.iwara.tv/video/ZaU08Arr1Nfktz)

**Comment by re-ovo** [comment]
😨 什么手机

**Comment by xiao-gy** [comment]
> 😨 什么手机

魅族 16th plus

但是我如果在小窗模式下播放视频然后全屏，就不会出现这种问题😂

**Comment by re-ovo** [comment]
是部分视频卡死，还是全部

**Comment by xiao-gy** [comment]
> 是部分视频卡死，还是全部

部分视频

**Comment by re-ovo** [comment]
不清楚什么问题，如果就你有这个问题，我也没办法，我也没办法复现

**Comment by xiao-gy** [comment]
> 不清楚什么问题，如果就你有这个问题，我也没办法，我也没办法复现

可以加入log抓取功能(?)，不然有bug确实不好反馈

**Comment by re-ovo** [comment]
> > 不清楚什么问题，如果就你有这个问题，我也没办法，我也没办法复现
> 
> 可以加入log抓取功能(?)，不然有bug确实不好反馈

如果你会adb的话，可以连接上，然后执行 `adb logcat >log.txt` 把日志打印出来

**Comment by xiao-gy** [comment]
> > > 不清楚什么问题，如果就你有这个问题，我也没办法，我也没办法复现
> > 
> > 
> > 可以加入log抓取功能(?)，不然有bug确实不好反馈
> 
> 如果你会adb的话，可以连接上，然后执行 `adb logcat > log.txt` 把日志打印出来

高三了😂时间不是很多，还是等等吧
