### ISSUE TITLE
1.0.5无法搜索和下载，登录后无反馈

### ISSUE THREAD

**Issue by 9rankk** [awara-app/awara#12]

**Comment by re-ovo** [comment]
下载功能根本就没做，但是搜索我做了，你确定你是1.0.5？

**Comment by 9rankk** [comment]
> 下载功能根本就没做，但是搜索我做了，你确定你是1.0.5？

哦抱歉，无法搜索是1.0.3遗留问题。
搜索得到的结果好像和以前有出入，是没接入先前的hentai日站点吗（ owo

**Comment by re-ovo** [comment]
用的官方的
