### ISSUE TITLE
1.0.6版本无法下载

### ISSUE THREAD

**Issue by Artillery666666** [awara-app/awara#13]
点击了下载没有任何反应。

**Comment by re-ovo** [comment]
开启通知权限，需要前台服务

**Comment by Artillery666666** [comment]
我下载下到一半就停止了，重复几次都是这样。还有，大佬能发下discord的群吗？我之前在群里的不知怎么就没了。

**Comment by re-ovo** [comment]
没有群
我下载是正常的，没发现这些问题

**Comment by re-ovo** [comment]
没日志我也不清楚啥原因

**Comment by History-exe** [comment]
其实app内下载不是十分必要。

你可以使用termux 安装yt-dlp通过命令行的方式下载大多数网站的视频，当然iwara的也是可以的。

如果你不知道具体的操作方法，可以找我，和我在电报上交流。

我的电报ID你需要找一找，没有隐藏，你点进我的GitHub资料里就应该能找到线索。
