### ISSUE TITLE
1.0.7视频标题显示不完整

### ISSUE THREAD

**Issue by silly486** [awara-app/awara#15]
在视频外时能正确显示全部标题文字，但是点进去之后标题就只能显示一行的内容，并不完整。
![IMG_20230504_230412](https://user-images.githubusercontent.com/105905446/236249399-dd402875-5700-46e5-ba39-3832256673ed.jpg)
![IMG_20230504_230423](https://user-images.githubusercontent.com/105905446/236249421-bcae56b1-d1d3-4a32-828a-8adfb0d60bb6.jpg)
![IMG_20230504_230614](https://user-images.githubusercontent.com/105905446/236249429-ca7a0163-d212-4171-8c78-f2230644dad3.jpg)
版本：1.0.7
手机型号：vivo neo3

**Comment by silly486** [comment]
不知道是刻意这样设计的还是什么，总之先发个issue问一下（

**Comment by silly486** [comment]
![Screenshot_20230504_232532](https://user-images.githubusercontent.com/105905446/236254751-64d1f8b6-fe75-4b8a-bfd6-a11ea76586e2.jpg)
另外，缓存后的视频播放时右上角这个全屏按钮（？）的位置可以改一下吗，我的手机在那里有个摄像头。

**Comment by re-ovo** [comment]
fixed
