### ISSUE TITLE
报告bug

### ISSUE THREAD

**Issue by liyonge5** [awara-app/awara#9]
进入播放界面 返回上一界面软件会卡死。有视频声音。但是在主页界面卡住了。还有点击作者头像进入作者主页也会卡死。还有关注列表是0。

**Comment by re-ovo** [comment]
没遇到过 😥

**Comment by re-ovo** [comment]
试试1.0.2

**Comment by xiao-gy** [comment]
我也遇到了一样的情况😭

### 设备

魅族 16th plus

### 系统

flyme9 测试版 （安卓10）

### 操作

点击视频横屏播放，然后点击退出横屏，手机直接卡死，只能锁屏重开

![S30430-21164925](https://user-images.githubusercontent.com/45650719/235354896-f75b5c34-dd0f-4e22-bb78-c3effba265f5.png)

退出横屏会直接卡在这里动不了

**Comment by xiao-gy** [comment]
> 我也遇到了一样的情况😭
> 
> ### 设备
> 魅族 16th plus
> 
> ### 系统
> flyme9 测试版 （安卓10）
> 
> ### 操作
> 点击视频横屏播放，然后点击退出横屏，手机直接卡死，只能锁屏重开
> 
> ![S30430-21164925](https://user-images.githubusercontent.com/45650719/235354896-f75b5c34-dd0f-4e22-bb78-c3effba265f5.png)
> 
> 退出横屏会直接卡在这里动不了

另一台手机 Redmi K40(安卓13)无此情况

**Comment by liyonge5** [comment]
1.0.4 版本
 安卓13 
手机 红魔8pro
还一样，不过不是卡死是未响应。播放视频然后，返回软件主页，视频还在后台播放没关闭 。造成软件未响应。等那视频播放结束或关闭。然后软件恢复正常。

**Comment by liyonge5** [comment]
![Screenshot_2023-04-30-16-17-25-519](https://user-images.githubusercontent.com/123760506/235358128-6abbf49a-802e-4b59-bd28-7120f45ef49c.jpg)

**Comment by re-ovo** [comment]
@liyonge5 @xiao-gy 进设置把动态颜色关掉看看

**Comment by liyonge5** [comment]
> @liyonge5 @xiao-gy 进设置把动态颜色关掉看看

关了。一样。

**Comment by re-ovo** [comment]
hmmm, 我猜测可能是DLNA投屏相关没有正确释放资源，可以加qq看看吗

**Comment by re-ovo** [comment]
试试1.0.5 @liyonge5

**Comment by liyonge5** [comment]
> 试试1.0.5 @liyonge5
问题解决 神速啊！大神👍

**Comment by liyonge5** [comment]
> 

好的进了discord 群了。不用QQ好多年。刚刚准备登录发现忘记密码了😂。

**Comment by xiao-gy** [comment]
> 试试1.0.5 @liyonge5

我用1.0.5会在刚开始播放视频手机卡死，但确实有声音在后台播放
